### ISSUE TITLE
Cadastro de restaurantes

### ISSUE THREAD

**Issue by TIwashima** [izumizawa/mc426y2023#4]
Essa funcionalidade tem o objetivo de efetuar o cadastro de restaurantes na nossa aplicação e desenvolver páginas iniciais que guiem e possibilitem o usuários a fazer o cadastro. 
Primeiro, a pessoa abre uma tela de boas vindas, que leva para o formulário de cadastro.
Este cadastro requer os seguintes campos:

- Nome de restaurante
- CNPJ
- Telefone
- Endereço (CEP, endereço, número, complemento, estado e cidade)

Ao clicar no botão de "cadastrar", deve enviar os dados ao banco.

**Comment by izumizawa** [comment]
Restaurant register API:

- Address
- Restaurant
- IdentityDocument
- Telephone
- Authentication

**Comment by izumizawa** [comment]
- [x] Cadastro com campos: CNPJ, nome, endereço, telefone e senha
- [ ] Inclusão de imagem de logo (opcional)
- [x] Boas vindas com botão para o cadastro

**Comment by izumizawa** [comment]
![Image](https://user-images.githubusercontent.com/42664943/234446940-d99c53e5-3508-4e37-8896-292b4c475ec9.png)

**Comment by JonasCardoso** [comment]
![image](https://user-images.githubusercontent.com/17953751/234723010-bf3df817-97a2-4fdd-8572-cad9025df658.png)
